### PR TITLE
Remove unused InventoryAdjustment, InventoryEventMessage and PurchaseOrderReceipt code

### PR DESCRIPTION
**Pull request by jordan-brough**
We don't seem to use this code and none of it is tested, so remove it.

@athal7 @philbirt -- I don't *think* we use this stuff at all but I really don't know.  Do either of you know for sure?

In any case though let's hold off on deploying this until we're sure the rest of our new code is working correctly.

### CODE REVIEW

**Comment by jordan-brough** [comment]
FYI I added some tracking in https://github.com/bonobos/quiet_logistics_integration/pull/10 so we can verify better whether some of this stuff is actually being used.

**Comment by athal7** [comment]
i don't believe that we do currently, but there have been some talks about starting to listen to specific inventory event messages from QL to get more accurate eCommerce stock

**Comment by jordan-brough** [comment]
@philbirt @athal7 - The tracking code hasn't recorded any usage in the past 4 days so I think this is safe to remove.  I also updated to remove PurchaseOrderReceipt as well since that is in the same bucket.  Look good?

**Comment by athal7** [comment]
yep!

**Pull request merged**
